os:
 - linux
 - osx
 - windows
language: node_js
node_js:
  - "11.4.0"
script:
  - npm run build
  - npm run test:coverage
  - npm run tslint
  - npm pack
after_success: 
  - npm run report-coverage
deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: brighterscript-*\.tgz
    skip_cleanup: true
    on:
      branch: master
      tags: true
      # only deploy from the linux build
      condition: $TRAVIS_OS_NAME = linux
  - provider: npm
    email: "bronley@gmail.com"
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      branch: master
      tags: true
      # only deploy from the linux build
      condition: $TRAVIS_OS_NAME = linux